### ISSUE TITLE
css todo

### ISSUE THREAD

**Issue by RobSprouse** [RobSprouse/Gaming-Holidays#1]
Edit the css file to format the singleGameCard and it's containing elements. The following fetch alters the following HTML code.

>fetch of a game by it's id
```javascript

fetch("https://api.rawg.io/api/games/3498?key=164d87e9b2364003ad69bc496d5e3d7f")
     .then((response) => response.json())
     .then((game) => {
          let singleGameCard = $("<div class='singleGameCard'>");
          singleGameCard.append(
               $("<img>", { class: "backgroundImage", src: game.background_image, alt: "background image" })
          );
          singleGameCard.append($("<h2 class='gameName'>").text(game.name));
          singleGameCard.append($("<p class='releasedDate'>").text(game.released));
          singleGameCard.append("<h3>Platforms</h3>");
          singleGameCard.append(
               $("<ul class='platformName'>").append(
                    $.map(game.platforms, function (platforms) {
                         return $("<li>").text(platforms.platform.name);
                    })
               )
          );
          singleGameCard.append("<h3>Tags</h3>");
          singleGameCard.append(
               $("<ul class = 'tags'>").append(
                    $.map(game.tags, function (tags) {
                         return $("<li>").text(tags.name);
                    })
               )
          );
          $(".gameCardsDiv").append(singleGameCard);
     })
     .catch((error) => console.error("Error:", error));
```
>before the fetch is ran
```html
<!DOCTYPE html>
<html lang="en">

<!-- COMMENT: Meta Data -->

<head>
     <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <!-- COMMENT: Linked Style Sheets -->
     <link rel="stylesheet" href="../assets/css/normalize.css">
     <link rel="stylesheet" href="style.css">
     <title>Gaming Holidays</title>
</head>

<!-- COMMENT: Body Section -->

<body>

     <!-- COMMENT: Header with Search-->
     <header>
          <h1>Gaming Holidays</h1>
          <p id="instructionsP">
               <span id="instructionsSpan">Directions:</span>
          </p>
          <section class="gameSearch">
               <h3>Search for a Game:
               </h3>
               <form id="searchInput">
                    <input type="text" name="searchInput" placeholder="Game Name" id="searchInput">
                    <input type="submit" value="Search">
               </form>
          </section>
     </header>

     <!-- COMMENT: Main Section-->
     <main>
          <!-- COMMENT: Game card display area -->
          <section class="categories">
          </section>
          <!-- COMMENT: Game card display area -->
          <section class="displayedResults">
               <section class="gameCardsDiv">
                    <!-- COMMENT: Where Game Cards will be appended -->
               </section>
               <section class="holidayDates"></section>
          </section>
     </main>
     <!-- COMMENT: Footer -->
     <footer>
          footer
     </footer>

     <!-- COMMENT: JS Scripts -->
     <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
     <script src="../assets/js/script.js"></script>
</body>

</html>
```

>after the fetch is ran
```html
<!DOCTYPE html>
<html lang="en">
     
<!-- COMMENT: Meta Data -->
<head>
     <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <!-- COMMENT: Linked Style Sheets -->
     <link rel="stylesheet" href="../assets/css/normalize.css">
     <link rel="stylesheet" href="style.css">
     <title>Gaming Holidays</title>
</head>

<!-- COMMENT: Body Section -->

<body>

     <!-- COMMENT: Header with Search-->
     <header>
          <h1>Gaming Holidays</h1>
          <p id="instructionsP">
               <span id="instructionsSpan">Directions:</span>
          </p>
          <section class="gameSearch">
               <h3>Search for a Game:
               </h3>
               <form id="searchInput">
                    <input type="text" name="searchInput" placeholder="Game Name" id="searchInput">
                    <input type="submit" value="Search">
               </form>
          </section>
     </header>

     <!-- COMMENT: Main Section-->
     <main>
          <!-- COMMENT: Game card display area -->
          <section class="categories">
          </section>
          <!-- COMMENT: Game card display area -->
          <section class="displayedResults">
               <section class="gameCardsDiv">
                    <!-- COMMENT: Where Game Cards will be appended -->
                    <div class="singleGameCard"><img class="backgroundImage"
                              src="https://media.rawg.io/media/games/20a/20aa03a10cda45239fe22d035c0ebe64.jpg"
                              alt="background image">
                         <h2 class="gameName">Grand Theft Auto V</h2>
                         <p class="releasedDate">2013-09-17</p>
                         <h3>Platforms</h3>
                         <ul class="platformName">
                              <li>PlayStation 5</li>
                              <li>Xbox Series S/X</li>
                              <li>PC</li>
                              <li>PlayStation 4</li>
                              <li>PlayStation 3</li>
                              <li>Xbox 360</li>
                              <li>Xbox One</li>
                         </ul>
                         <h3>Tags</h3>
                         <ul class="tags">
                              <li>Singleplayer</li>
                              <li>Steam Achievements</li>
                              <li>Multiplayer</li>
                              <li>Full controller support</li>
                              <li>Atmospheric</li>
                              <li>Great Soundtrack</li>
                              <li>RPG</li>
                              <li>Co-op</li>
                              <li>Open World</li>
                              <li>cooperative</li>
                              <li>First-Person</li>
                              <li>Third Person</li>
                              <li>Funny</li>
                              <li>Sandbox</li>
                              <li>Comedy</li>
                              <li>Third-Person Shooter</li>
                              <li>Moddable</li>
                              <li>Crime</li>
                              <li>vr mod</li>
                         </ul>
                    </div>
               </section>
               <section class="holidayDates"></section>
          </section>
     </main>
     <!-- COMMENT: Footer -->
     <footer>
          footer
     </footer>

     <!-- COMMENT: JS Scripts -->
     <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
     <script src="../assets/js/script.js"></script>


</body>

</html>
```

>latest css changes I made, I misspelled something originally which didn't give you the correct starting code
```css
/* COMMENT:Root and Initial Elements */
:root {
     --Header-footer-font: "'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif";
     --Body-font: "'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif";
}

@media screen {
     body {
          margin: 5% 5%;
     }
}

* {
     box-sizing: border-box;
     padding: 0;
     margin: 0;
     color: #413a3a;
     list-style: none;
}

/* COMMENT: Body Section*/
body {
     display: flex;
     flex-direction: column;
     font-family: var(--Body-font);
     border: 1px solid white;
     background-color: black;
}

/* COMMENT: Header with City Search */
header {
     display: flex;
     flex-direction: column;
     background-color: grey;
     border: 1px solid white;
     align-items: center;

}

#instructionsP {
     text-align: justify;
     padding: 0 3em 1em 3em;
}

#instructionsSpan {
     color: blue;
     font-weight: bold;
     font-size: 20px;
}

header section {
     padding: 0 3em 1em 3em;
}

#invalidEntry {
     padding: 0.5em 0 0.5em 0;
}


.gameSearch {
     display: flex;
     flex: 1 0 auto;
     flex-direction: row;
     align-items: center;
     text-align: center;
     padding: 1em 0 0.5em 0;
}

#searchInput input[type=text] {
     max-width: 12em;
     margin-left: 0.2em;
}

/* COMMENT: Main Section */
main {
     display: flex;
     flex-direction: row;
}

/* COMMENT: Search area */

.categories {
     display: flex;
     flex-direction: column;
     flex-basis: 20%;
     align-items: center;
     background-color: rgb(88, 88, 88);
     border: 1px solid white;
     padding: 0.5em;
     min-width: 8em;
}

/* COMMENT: Gamecard display area parent div */
.displayedResults {
     display: flex;
     flex: 1 1 100%;
     flex-direction: column;
     background-color: grey;
     border: 1px solid white;
     min-height: 50em;


}


/* COMMENT: Game card display area */
.gameCardsDiv {
     display: flex;
     flex-direction: row;
     flex-wrap: wrap;
     justify-content: space-around;
}

/* COMMENT: Individual Game Cards */
.singleGameCard {
     display: flex;
     flex-direction: column;
     flex: 0 0 auto;
     min-width: 8em;
     min-height: 10em;
     margin: 0.5em 0.5em;
     background-color: rgb(73, 73, 73);
     padding: 0.5em;
     justify-content: space-between;

}

.backgroundImage {
     max-width: 100px;
     margin: 0 0 0 2em;
}


/* COMMENT: Footer */
footer {
     display: flex;
     background-color: rgb(88, 88, 88);
     border: 1px solid white;
     min-height: 4em;
}
```
